[package]
name = "aio-limited"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
futures = "0.1"
log = ">= 0.4"
parking_lot = "0.5"
tokio-executor = "0.1"
tokio-io = "0.1"
tokio-timer = "0.2"

[dev-dependencies]
env_logger = "0.5"
tokio = "0.1"

