[package]
name = "aio-limited"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
log = ">= 0.4"
quick-error= "1"
parking_lot = "0.5"
tokio = ">= 0.1.5"

[dev-dependencies]
env_logger = "0.5"

